version: "3"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
  frontend:
    build: ./frontend
    env_file:
      - .env
    ports: 
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    depends_on:
      - backend